


/* CREATE DATA BASE FOR TEST */
create database DB_TEST

/* CREATE DATA BASE FOR TEST IF YOU WANT TO MAKE QUERIES*/
USE DB_TEST


/* 
THIS CREATE DATABASE SCRIPT IS MAINLY FOR MODEL FIRST APROACH, SO NO NEED TO WRITE
SQL SERVER SCRIPTS, ALL IS IN THE OBJECT MODEL ENTITIES ON BACK END CODE.
*/


