version: '3.7'
services:
    MSSQLSERVER2019:
        image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
        container_name: MsSqlServer2019
        environment:
          SA_PASSWORD: "Password0!"
          ACCEPT_EULA: "Y"
        ports:
         - "1433:1433"
        volumes:
         - C:\DOCKER-COMPOSE\MSSQLSERVER\data:/var/opt/mssql/data